- hosts: all
  become: true
  tasks:

  - name: Install Java 21
    apt:
      name: openjdk-21-jre-headless
      state: present
      update_cache: yes

  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.108/bin/apache-tomcat-9.0.108.tar.gz
      dest: /tmp/apache-tomcat-9.0.108.tar.gz
      mode: '0644'

  - name: Extract Tomcat
    unarchive:
      src: /tmp/apache-tomcat-9.0.108.tar.gz
      dest: /opt
      remote_src: yes
      owner: ubuntu
      group: ubuntu
      mode: '0755'

  - name: Rename Tomcat directory
    command: mv /opt/apache-tomcat-9.0.108 /opt/tomcat
    args:
      creates: /opt/tomcat

  - name: Ensure Tomcat ownership
    file:
      path: /opt/tomcat
      state: directory
      owner: ubuntu
      group: ubuntu
      recurse: yes

  - name: Create Tomcat systemd service file
    copy:
      dest: /etc/systemd/system/tomcat.service
      content: |
        [Unit]
        Description=Apache Tomcat Web Application Container
        After=network.target

        [Service]
        Type=simple
        User=ubuntu
        Group=ubuntu
        Environment=JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        Environment=CATALINA_HOME=/opt/tomcat
        ExecStart=/opt/tomcat/bin/catalina.sh run
        ExecStop=/opt/tomcat/bin/shutdown.sh
        Restart=always

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd to pick up Tomcat service
    command: systemctl daemon-reload

  - name: Start and enable Tomcat service
    service:
      name: tomcat
      state: started
      enabled: yes
